import "./globals.css";
import Header from "@/components/global-layout/Header";
import Footer from "@/components/global-layout/Footer";
import { fetchGlobalData } from "@/lib/api";
import { languages } from "@/config/languages";

export async function generateMetadata({ params }) {
  const { lang } = await params;
  const globalData = await fetchGlobalData(lang);

  return {
    title: globalData.seo?.title || "Create Next App",
    description: globalData.seo?.description || "Generated by create next app",
  };
}

export async function generateStaticParams() {
  return languages.map((lang) => ({ lang: lang.code }));
}

export default async function RootLayout({ children, params }) {
  const { lang } = await params;
  const languageConfig =
    languages.find((language) => language.code === lang) || {};
  const direction = languageConfig.dir || "ltr";
  const globalData = await fetchGlobalData(lang);

  return (
    <html lang={lang} dir={direction}>
      <body>
        <main className="m-0 p-0 w-full ">
          <div className="w-full mx-auto">
            <Header
              header={globalData.header}
              lang={lang}
              direction={direction}
            />
            <main className="min-h-screen">{children}</main>
            <Footer footer={globalData.footer} lang={lang} />
          </div>
        </main>
      </body>
    </html>
  );
}
