import "./globals.css";
import Header from "@/components/global-layout/Header";
import Footer from "@/components/global-layout/Footer";
import { fetchGlobalData, fetchLocales } from "@/lib/api";

// export async function generateMetadata({ params }) {
//   const { lang } = params;
//   const globalData = await fetchGlobalData(lang);

//   return {
//     title: globalData?.seo?.title || "Create Next App",
//     description: globalData?.seo?.description || "Generated by create next app",
//   };
// }

// export async function generateStaticParams() {
//   const locales = await fetchLocales();
//   const _locales = locales.map(({ code }) => ({ lang: code }));
//   console.log("All locales are : ", _locales);
//   return _locales;
// }

export default async function RootLayout({ children, params }) {
  const { lang } = await params;

  const [locales, globalData] = await Promise.all([
    fetchLocales(),
    fetchGlobalData(lang),
  ]);

  const languageConfig = locales.find(({ code }) => code === lang) || {};
  const direction = languageConfig?.dir || "ltr";
  return (
    <html lang={lang} dir={direction}>
      <body>
        <Header header={globalData?.header} lang={lang} direction={direction} />
        <main className="min-h-screen">{children}</main>
        <Footer footer={globalData?.footer} lang={lang} />
      </body>
    </html>
  );
}
