export const revalidate = 21600; //3600 * 6;
import "./globals.css";
import Header from "@/components/global-layout/Header";
import Footer from "@/components/global-layout/Footer";
import { fetchGlobalData, fetchLocales } from "@/lib/api";

export async function generateMetadata({ params }) {
  const { lang } = await params;
  const globalData = await fetchGlobalData(lang);

  return {
    title: globalData.seo?.title || "Create Next App",
    description: globalData.seo?.description || "Generated by create next app",
  };
}

export async function generateStaticParams() {
  const locales = await fetchLocales();
  return locales.map((locale) => ({ lang: locale.code }));
}

export default async function RootLayout({ children, params }) {
  const { lang } = await params;
  const languageConfig = await fetchLocales().then(
    (locales) => locales.find((language) => language.code === lang) || {}
  );
  const direction = languageConfig.dir || "ltr";
  const globalData = await fetchGlobalData(lang);

  return (
    <html lang={lang} dir={direction}>
      <body>
        <main className="m-0 p-0 w-full ">
          <div className="w-full mx-auto">
            <Header
              header={globalData.header}
              lang={lang}
              direction={direction}
            />
            <main className="min-h-screen">{children}</main>
            <Footer footer={globalData.footer} lang={lang} />
          </div>
        </main>
      </body>
    </html>
  );
}
