export const languages = [
  { code: "en", name: "English", flag: "/flags/en.png" },
  { code: "ar", name: "Arabic", dir: "rtl", flag: "/flags/ar.png" },
  { code: "de", name: "German", flag: "/flags/de.png" },
  { code: "fr", name: "French", flag: "/flags/fr.png" },
  { code: "es", name: "Spanish", flag: "/flags/es.png" },
  { code: "it", name: "Italian", flag: "/flags/it.png" },
  { code: "pt", name: "Portuguese", flag: "/flags/pt.png" },
  { code: "ru", name: "Russian", flag: "/flags/ru.png" },
  { code: "zh", name: "Chinese", flag: "/flags/zh.png" },
  { code: "ja", name: "Japanese", flag: "/flags/ja.png" },
  { code: "ko", name: "Korean", flag: "/flags/ko.png" },
  { code: "hi", name: "Hindi", flag: "/flags/hi.png" },
  { code: "bn", name: "Bengali", flag: "/flags/bn.png" },
  { code: "tr", name: "Turkish", flag: "/flags/tr.png" },
  { code: "pl", name: "Polish", flag: "/flags/pl.png" },
  { code: "sv", name: "Swedish", flag: "/flags/sv.png" },
  { code: "no", name: "Norwegian", flag: "/flags/no.png" },
  { code: "da", name: "Danish", flag: "/flags/da.png" },
  { code: "fi", name: "Finnish", flag: "/flags/fi.png" },
  { code: "nl", name: "Dutch", flag: "/flags/nl.png" },
  { code: "cs", name: "Czech", flag: "/flags/cs.png" },
  { code: "el", name: "Greek", flag: "/flags/el.png" },
  { code: "he", name: "Hebrew", dir: "rtl", flag: "/flags/he.png" },
  { code: "th", name: "Thai", flag: "/flags/th.png" },
  { code: "id", name: "Indonesian", flag: "/flags/id.png" },
  { code: "vi", name: "Vietnamese", flag: "/flags/vi.png" },
  { code: "ms", name: "Malay", flag: "/flags/ms.png" },
  { code: "ro", name: "Romanian", flag: "/flags/ro.png" },
  { code: "sr", name: "Serbian", flag: "/flags/sr.png" },
  { code: "hr", name: "Croatian", flag: "/flags/hr.png" },
  { code: "uk", name: "Ukrainian", flag: "/flags/uk.png" },
  { code: "bg", name: "Bulgarian", flag: "/flags/bg.png" },
  { code: "mk", name: "Macedonian", flag: "/flags/mk.png" },
  { code: "sq", name: "Albanian", flag: "/flags/sq.png" },
  { code: "hy", name: "Armenian", flag: "/flags/hy.png" },
  { code: "ka", name: "Georgian", flag: "/flags/ka.png" },
  { code: "ml", name: "Malayalam", flag: "/flags/ml.png" },
  { code: "ta", name: "Tamil", flag: "/flags/ta.png" },
  { code: "te", name: "Telugu", flag: "/flags/te.png" },
  { code: "mr", name: "Marathi", flag: "/flags/mr.png" },
  { code: "gu", name: "Gujarati", flag: "/flags/gu.png" },
  { code: "pa", name: "Punjabi", flag: "/flags/pa.png" },
  { code: "kn", name: "Kannada", flag: "/flags/kn.png" },
  { code: "ur", name: "Urdu", dir: "rtl", flag: "/flags/ur.png" },
  { code: "cy", name: "Welsh", flag: "/flags/cy.png" },
  { code: "eu", name: "Basque", flag: "/flags/eu.png" },
  { code: "gl", name: "Galician", flag: "/flags/gl.png" },
  { code: "la", name: "Latin", flag: "/flags/la.png" },
  { code: "is", name: "Icelandic", flag: "/flags/is.png" },
  { code: "lv", name: "Latvian", flag: "/flags/lv.png" },
  { code: "lt", name: "Lithuanian", flag: "/flags/lt.png" },
  { code: "et", name: "Estonian", flag: "/flags/et.png" },
  { code: "sk", name: "Slovak", flag: "/flags/sk.png" },
  { code: "sl", name: "Slovenian", flag: "/flags/sl.png" },
  { code: "sr", name: "Serbian", flag: "/flags/sr.png" },
  { code: "mt", name: "Maltese", flag: "/flags/mt.png" },
  { code: "hy", name: "Armenian", flag: "/flags/hy.png" },
  { code: "ne", name: "Nepali", flag: "/flags/ne.png" },
  { code: "si", name: "Sinhalese", flag: "/flags/si.png" },
  { code: "my", name: "Burmese", flag: "/flags/my.png" },
  { code: "lo", name: "Lao", flag: "/flags/lo.png" },
  { code: "km", name: "Khmer", flag: "/flags/km.png" },
  { code: "bs", name: "Bosnian", flag: "/flags/bs.png" },
  { code: "hr", name: "Croatian", flag: "/flags/hr.png" },
];

export const defaultLanguage = "en";
